### ISSUE TITLE
createSignature's options params is not working

### ISSUE THREAD

**Issue by cybriz** [chamodanethra/biometric_signature#1]
![Screen Shot 2023-02-07 at 2 46 54 PM](https://user-images.githubusercontent.com/34927951/217183229-36b9addc-58b5-4823-bfec-b8a8193566f4.png)

hihi, you forgot to include the options in the "createSignature" invokeMethod like shown in above pic.

**Comment by chamodanethra** [comment]
> ![Screen Shot 2023-02-07 at 2 46 54 PM](https://user-images.githubusercontent.com/34927951/217183229-36b9addc-58b5-4823-bfec-b8a8193566f4.png)
> 
> hihi, you forgot to include the options in the "createSignature" invokeMethod like shown in above pic.

@cybriz , Sounds reasonable. Even when calling Flutter's inbuilt compute function, argument for calling the actual computed function is passed like this.  Let me check and put in a new release.
