### ISSUE TITLE
always error in createSignature

### ISSUE THREAD

**Issue by rockyip** [chamodanethra/biometric_signature#18]
I follow the example to  create a public Key then createSignature
After face ID dialog is prompted and success,
it then throw below error whici I dun understand what's wrong from the code.

flutter: Error decrypting RSA private key: The operation couldn’t be completed. (OSStatus error -50 - ECIES: Failed to aes-gcm decrypt data (err -69))

I am using real device, iPhone 13 Pro Max with iOS 17.5.1.
The version of biometric_signature is 5.1.1

**Comment by rockyip** [comment]
I finally can use createSignature without errors after called deleteKeys.
But I still dun understand why I need to delete the keys

**Comment by chamodanethra** [comment]
> I follow the example to create a public Key then createSignature After face ID dialog is prompted and success, it then throw below error whici I dun understand what's wrong from the code.
> 
> flutter: Error decrypting RSA private key: The operation couldn’t be completed. (OSStatus error -50 - ECIES: Failed to aes-gcm decrypt data (err -69))
> 
> I am using real device, iPhone 13 Pro Max with iOS 17.5.1. The version of biometric_signature is 5.1.1


You have to pass a **String Boolean("true", "True", "yes" etc.)** as per iOS documentation as the **value** of the String **key** called `"shouldMigrate"` inside the Dart payload passed down to `createSingature(options: Map<String, String>)` function call. I did test this scenario manually myself before publishing version the 5.1.0. Then I upgraded the readMe file with that [instruction.](https://github.com/chamodanethra/biometric_signature#:~:text=shouldMigrate%3A%20(iOS%20only%2C%20required)%3A%20To%20migrate%20to%20Secure%20Enclave%20implementation%20from%20the%20Key%20Chain%20implementation%20used%20prior%20to%20version%205.0.0%2C%20need%20to%20pass%20a%20valid%2C%20positive%20String%20Bool(as%20per%20Swift%20Official%20docs).)
