### ISSUE TITLE
[BUG] - iOS: Error decrypting RSA private key

### ISSUE THREAD

**Issue by samueldubovec-embedit** [chamodanethra/biometric_signature#20]
Hey,

when calling createSignature function after generating new key-pair on iOS sometimes (it doesn't happen all the time) I get error:

Error decrypting RSA private key: The operation couldn’t be completed. (OSStatus error -50 - ECIES: Failed to aes-gcm decrypt data (err -69))

There is no problem on Android devices, so probably it's related to secure enclave

I'm using latest version (5.1.1) of package.

Thank you.

**Comment by samueldubovec-embedit** [comment]
I think that it happens when you have the key-pair generated (let's say you have installed application, delete it - keys are not deleted as are in the keychain).
After installing application again, you generate new key pair (which should also delete already existing key-pair).
The new (public key is generated successfully, I compared that is not same as previous one). After that the error occures.

**Comment by chamodanethra** [comment]
@samueldubovec-embedit, as of now (version 5.1.1), you need to manually call deleteKeys() function from your Flutter code to tackle your scenario. Will be putting a patch fix version soon addressing this issue.

**Comment by chamodanethra** [comment]
https://pub.dev/packages/biometric_signature/versions/5.1.2 has addressed this concern, @samueldubovec-embedit. So this issue will be closed.
