### ISSUE TITLE
The ability to enter a PIN code or a graphic key on the android

### ISSUE THREAD

**Issue by zakharov161** [chamodanethra/biometric_signature#23]
Hi. Please add DEVICE_CREDENTIALS as an alternative authorization method. This will be useful when the user of an android device does not have support for facial biometrics or problems with the fingerprint sensor.

**Comment by chamodanethra** [comment]
@zakharov161, you have to use biometric Strong authentication available in an Android Device to perform plugin's underlying cryptographic operations. Thus your request becomes invalid.
