### ISSUE TITLE
Not detecting faceid on android

### ISSUE THREAD

**Issue by narmadakit** [chamodanethra/biometric_signature#8]
It is detecting faceid on ios but for android detecting only fingerprint but not faceid.

**Comment by chamodanethra** [comment]
@narmadakit , could you please reveal the Android device model you checked on? This plugin works with only BIOMETRIC_STRONG. Check this [SO post](https://stackoverflow.com/questions/68904823/which-android-device-has-biometric-strong-class-3-face-authentication) for context.

**Comment by narmadakit** [comment]
android device is OnePlus Nord CE 2 Lite 5G

**Comment by narmadakit** [comment]
> @narmadakit , could you please reveal the Android device model you checked on? This plugin works with only BIOMETRIC_STRONG. Check this [SO post](https://stackoverflow.com/questions/68904823/which-android-device-has-biometric-strong-class-3-face-authentication) for context.


android device is OnePlus Nord CE 2 Lite 5G

**Comment by narmadakit** [comment]
> > @narmadakit , could you please reveal the Android device model you checked on? This plugin works with only BIOMETRIC_STRONG. Check this [SO post](https://stackoverflow.com/questions/68904823/which-android-device-has-biometric-strong-class-3-face-authentication) for context.
> 
> android device is OnePlus Nord CE 2 Lite 5G, OxygenOS 14.0 version ..Thanks in advance
